

export enum Role {
    ADMIN = "Admin",
    SALER = "Saler",
    USER = "User",
}

export enum PaymentStatus {
    CANCELLED = "CANCELLED",
    PENDING = "PENDING",
    SUCCESS = "PAID",
    EXPIRED = "EXPIRED"
}

export enum ProductStatus {
    AVAILABLE = "AVAILABLE",
    UNAVAILABLE = "UNAVAILABLE",
    SOLD_OUT = "SOLD_OUT",
    COMING_SOON = "COMING_SOON",
}

export enum BillStatus {
    PENDING = "PENDING",
    SHIPPING = "SHIPPING",
    DELIVERED = "DELIVERED",
    USER_CANCELLED = "USER_CANCELLED",
    USER_RETURN_PENDING = "USER_RETURN_PENDING",
    USER_RETURN_CONFIRMED = "USER_RETURN_CONFIRMED",
    SELLER_CANCELLED = "SELLER_CANCELLED",
    SELLER_RETURN_PENDING = "SELLER_RETURN_PENDING",
    SELLER_RETURN_ACCEPTED = "SELLER_RETURN_ACCEPTED",
    SELLER_RETURN_REJECTED = "SELLER_RETURN_REJECTED",
    
}